### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jaychokshi** [johnyf/pycflow2dot#7]
```
$ cflow2dot.exe -i temp.c -f png
Traceback (most recent call last):
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jchokshi\AppData\Local\Programs\Python\Python35\Scripts\cflow2dot.exe\__main__.py", line 9, in <module>
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\site-packages\pycflow2dot.py", line 531, in main
    preprocess=preproc)
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\site-packages\pycflow2dot.py", line 83, in call_cflow
    cflow_data = subprocess.check_output(cflow_cmd)
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "c:\users\jchokshi\appdata\local\programs\python\python35\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
cflow2dot
found cflow at: /usr/local/bin/cflow
found dot at: /cygdrive/c/Program Files (x86)/Graphviz2.38/bin/dot
```

**Comment by jaychokshi** [comment]
Nevermind. Its environment issue with Cygwin
