### ISSUE TITLE
[CRASH] AssertionError in _annotate_nodes_with_filename

### ISSUE THREAD

**Issue by ildar** [johnyf/pycflow2dot#9]
in https://github.com/adafruit/Adafruit_nRF52_Bootloader tree I do:
> pycflow2dot.py -f png --merge --source main -i `find -name '*.c'`

and get:
```
Traceback (most recent call last):
  File "/home/ildar/bin/pycflow2dot.py", line 691, in <module>
    main()
  File "/home/ildar/bin/pycflow2dot.py", line 678, in main
    g = _merge_graphs(graphs, c_fnames)
  File "/home/ildar/bin/pycflow2dot.py", line 386, in _merge_graphs
    _annotate_nodes_with_filename(g, graph, c_fname)
  File "/home/ildar/bin/pycflow2dot.py", line 408, in _annotate_nodes_with_filename
    assert 'file_name' not in dg, dg
AssertionError: {'nest_level': 1, 'src_line': 218, 'file_name': './lib/sdk11/components/libraries/bootloader_dfu/dfu_transport_serial.c'}
```

**Comment by johnyf** [comment]
Thank you for reporting this behavior. I get a similar error from commit https://github.com/adafruit/Adafruit_nRF52_Bootloader/commit/5e6690e2967484269659d2b49e400b8372f88208 using (a code block enables rendering the backticks, which otherwise are interpreted as delimiters of inline code):

```shell
cflow2dot -f png --merge --source main -i `gfind -name '*.c'`
```

for another file in the repository `Adafruit_nRF52_Bootloader` than the file `dfu_transport_serial.c` that appears in the OP. This behavior is with `pycflow2dot==0.2.3`.
([`gfind`](https://ports.macports.org/port/findutils/summary) is the [GNU `find`](https://www.gnu.org/software/findutils/) available via the [MacPorts](https://www.macports.org/) package `findutils` on macOS.)

Regarding the call to the script `pycflow2dot.py`, please note that `pip install pycflow2dot` installs an executable Python script named `cflow2dot` under Python's `bin/` directory.
